### ISSUE TITLE
Chrome fails to install

### ISSUE THREAD

**Issue by jakepusateri** [mklabs/webpagetest-xvfb#1]
As of yesterday, the script used to install chrome released 7.0, which requires CentOS 6.6. http://chrome.richardlloyd.org.uk/. This causes the install of Chrome to hang. Upgrading the Vagrantfile to CentOS 6.6 appears to solve the problem.

**Comment by mklabs** [comment]
Hello @jakepusateri 

Glad to hear you found a workaround. I'd more than happy to accept a PR if you'd like to do so, otherwise I'll take care of that later this week.
