### ISSUE TITLE
Start render always 0 seconds

### ISSUE THREAD

**Issue by JakeChampion** [mklabs/webpagetest-xvfb#2]
I've got this up and running using centos 6.6 however every site I tested (I've tested 10,000) comes back with a start render time of 0.00 seconds.

Is this something others are seeing?

**Comment by mklabs** [comment]
Hello @JakeChampion 

Yes, the nodejs agent is still considered experimental. To fix it, we'd need to dig in https://github.com/WPO-Foundation/webpagetest/tree/master/agent/js

**Comment by mklabs** [comment]
and probably open an issue there :) I can't reproduce this issue right now.

https://github.com/WPO-Foundation/webpagetest/issues?q=is%3Aopen+is%3Aissue+label%3ANodeJS
